services:
  - type: web
    name: hrmproject
    env: php
    plan: free
    branch: main

    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan key:generate
      php artisan config:clear
      php artisan cache:clear

    startCommand: php artisan serve --host 0.0.0.0 --port $PORT

